name: CD Workflow
on:
  push:
    branches:
      - none

jobs:
  deploy:
    name: 🚀 Deploy to App Engine
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup
        run: npm install
      - name: Environment variables injection
        uses: golang-enthusiast/app-yaml-env-compiler@v1.0
        env:
          NODE_ENV: production
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION_MINUTES: ${{ secrets.JWT_EXPIRATION_MINUTES }}
          JWT_REFRESH_TOKEN_EXPIRATION_DAYS: ${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION_DAYS }}
      - name: List dependencies
        run: npm list
      - name: build
        run: npm run build
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.PROJECT_GCP_ID }}
          credentials: ${{ secrets.PROJECT_GCP_KEY }}
          promote: false
          version: v1
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
